name: 🤗 Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Push to hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push -f https://QuangDinh2102:$HF_TOKEN@huggingface.co/spaces/QuangDinh2102/EXE_CVMatching_backend main